spring.kakao.pay.cid=${KAKAO_PAY_CID}
spring.kakao.pay.cid.secret=${KAKAO_PAY_CID_SECRET}

spring.ncloud.sms.access.key=${NCLOUD_SMS_ACCESS_KEY}
spring.ncloud.sms.secret.key=${NCLOUD_SMS_SECRET_KEY}
spring.ncloud.sms.service.id=${NCLOUD_SMS_SERVICE_ID}

spring.cool.sms.phone.from=${COOL_SMS_PHONE_FROM}
spring.cool.sms.api.key=${COOL_SMS_API_KEY}
spring.cool.sms.api.secret=${COOL_SMS_API_SECRET}
