spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_db
    username: postgres
    password: zena0116@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

jwt:
  secret:
    salt: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M # 확인해보고 변경하기
