cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
aws.sqs.queues.notifications=${AWS_SQS_QUEUE_NOTIFICATIONS}
aws.sqs.queues.chat-messages=${AWS_SQS_QUEUE_CHAT_MESSAGES}
aws.sqs.queues.chat-events=${AWS_SQS_QUEUE_CHAT_EVENTS}
