spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
  batch:
    job:
      name: ${job.name:NONE}
    jdbc:
      initialize-schema: always

logging:
  level:
    root: INFO
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging.level:
  org.hibernate.SQL: debug

jwt:
  secret:
    salt: ${JWT_SECRET}
