bootJar { enabled = false }
jar { enabled = true }

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':spring-core')

    runtimeOnly 'org.postgresql:postgresql'

    annotationProcessor "jakarta.annotation:jakarta.annotation-api"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"

    annotationProcessor 'org.projectlombok:lombok'

    implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
    annotationProcessor "com.querydsl:querydsl-apt:5.0.0:jakarta"

    testImplementation 'org.assertj:assertj-core'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.3'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.9.3'

    implementation 'com.github.f4b6a3:ulid-creator:5.2.0'

}

tasks.register("prepareKotlinBuildScriptModel") {}

def generated = "$projectDir/src/main/generated"

tasks.withType(JavaCompile) {
    options.getGeneratedSourceOutputDirectory().set(file(generated))
}

sourceSets {
    main.java.srcDirs += [generated]
}

clean {
    delete file(generated)
}
